GET http://localhost:5050/users

###############

POST http://localhost:5050/users/new HTTP/1.1
content-type: application/json

{
    "firstName":"Adriana",
    "lastName":"Benedetti",
    "username":"Adrianab",
    "email":"adriana@gmail.com",
    "password":"123",
}

########